unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix
set-option -sg escape-time 0
set-option -g focus-events on
set -g renumber-windows on
set -g history-limit 50000
set -g mouse on

set -g status-justify absolute-centre
set -g status-style 'fg=color7 bg=default'
set -g status-right ''
# set -g status-right ' #(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD)'
# set -g status-right ''
set -g status-left '#S'
set -g status-left-style 'fg=color8'
set -g status-right-length 0
set -g status-left-length 100
setw -g window-status-current-style 'fg=colour6 bg=default bold'
setw -g window-status-current-format '#I:#W '
setw -g window-status-style 'fg=color8'

bind-key -n C-g run "~/.config/scripts/open-github.sh"
bind-key -n C-f run-shell "tmux neww '~/.config/scripts/sessionizer.sh'"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.config/tmux/plugins/tpm/tpm'
